# Generated by Django 2.2.2 on 2019-06-09 02:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_Post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='promocode',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
