# Generated by Django 2.2.2 on 2019-06-09 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20190609_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='promocode',
        ),
    ]
